### ISSUE TITLE
bosch_examples gives a "TypeError: 'module' object is not callable"

### ISSUE THREAD

**Issue by papamaeusebaer** [bosch-thermostat/bosch-thermostat-client-python#1]
/usr/local/bin/bosch_examples sensors --ip xxx.xxx.xxx.xxx --token xxx-xxx-xxx-xxx -password xxxxxxxxx -s energyConsumption
Traceback (most recent call last):
  File "/usr/local/bin/bosch_examples", line 10, in <module>
    sys.exit(cli())
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/bosch_thermostat_client/bosch_examples.py", line 29, in wrapper
    return asyncio.run(f(*args, **kwargs))
  File "/usr/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.7/dist-packages/bosch_thermostat_client/bosch_examples.py", line 59, in sensors
    session=session, host=ip, access_key=token, password=password
TypeError: 'module' object is not callable

The error is from an Raspberry, Raspbian GNU/Linux 10 (buster), with Python 3.7.3.

**Comment by pszafer** [comment]
I forgot to update bosch_examples after adding support for NEFIT devices. I will do that next week.

**Comment by pszafer** [comment]
I dropped bosch_examples.
Now you can run just
```
bosch_cli query --host --token --password --path /system/sensors/outdoorTemperatures/t1
```
