### ISSUE TITLE
CT100: AttributeError: 'NefitCircuit' object has no attribute '_schedule

### ISSUE THREAD

**Issue by marcomsousa** [bosch-thermostat/bosch-thermostat-client-python#10]
In the HA logs, I see this error every minute:

```
2021-01-11 14:56:24 ERROR (MainThread) [bosch_thermostat_client.connectors.xmpp] 400 HTTP Error - ['HTTP/1.0 400 Bad Request', 'Content-Type: application/json', 'connection: close', '', '']
2021-01-11 14:56:25 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/config/custom_components/bosch/__init__.py", line 277, in thermostat_refresh
await self.component_update(CLIMATE, event_time)
File "/config/custom_components/bosch/__init__.py", line 255, in component_update
await entity.bosch_object.update()
File "/usr/local/lib/python3.8/site-packages/bosch_thermostat_client/circuits/circuit.py", line 242, in update
if self._schedule:
AttributeError: 'NefitCircuit' object has no attribute '_schedule'
```
I think because of this, the climate info is not always updated.

I have a Junkers CT100 Firmware: 02.19.01

**Comment by pszafer** [comment]
Fixed in 0.10.0
